<a href="https://colab.research.google.com/github/MohammedAdnan51/PyTorch/blob/main/Py_Torch_2%263.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)


2.1.0+cu121


Creating Range of Tensors

In [2]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
range_tensors=torch.arange(start=0,end=1000,step=120)
range_tensors

tensor([  0, 120, 240, 360, 480, 600, 720, 840, 960])

In [4]:
#creating tensors Like
ten_zeroes=torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [5]:
#flaot 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [6]:
float_32_tensor.dtype

torch.float32

In [7]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [8]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [9]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [10]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])

###Getting Information from sensors
### tensor.dtype , tensor.shape ,tensor.device

In [11]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.2703, 0.9421, 0.1965, 0.2979],
        [0.9870, 0.4101, 0.5623, 0.9565],
        [0.7442, 0.9450, 0.7584, 0.7895]])

In [12]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [13]:
some_tensor.size()

torch.Size([3, 4])

In [14]:
#finding details of tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2703, 0.9421, 0.1965, 0.2979],
        [0.9870, 0.4101, 0.5623, 0.9565],
        [0.7442, 0.9450, 0.7584, 0.7895]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


manipulation of tensors

Tensors operations include:

*  Addittion

*  Subraction

*  Multiplication

*  Division

*   Matix Multiplication
















In [15]:
#create a tensor and add
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [16]:
# Multiply
tensor *10

tensor([10, 20, 30])

In [17]:
tensor-10

tensor([-9, -8, -7])

In [18]:
tensor /10

tensor([0.1000, 0.2000, 0.3000])

In [19]:
#pytorch Inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [20]:
torch.add(tensor,20)

tensor([21, 22, 23])

#Matrix Multiplication

Two main methods for  multiplication in neural networks and deep leaning:


1.   Element Wise Multiplication
2.   Matrix Multiplication(dot product)



In [21]:
#Element multiplication
print(tensor,'*',tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [22]:
#matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

#matrix multiplication by self

In [23]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.62 ms, sys: 0 ns, total: 1.62 ms
Wall time: 1.66 ms


In [24]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.1 ms, sys: 0 ns, total: 1.1 ms
Wall time: 1.11 ms


tensor(14)

In [25]:
# we can also use "@" for matrix multiplication
tensor @ tensor
#torch.mm(tensor,tensor)

tensor(14)

#matrix Multiplication dealing with tensor


In [26]:
tensor_A =torch.tensor([[1,3],
                       [2,4],
                       [5,7]])
tensor_B =torch.tensor([[2,3],
                       [3,4],
                       [5,6]])
#torch.matmul(tensor_A, tensor_B)

so the tensor_A and tensor_B can't be multiplied due to same shape

In [27]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

#To fix this shape issue we can use transpose .

In [28]:
tensor_B

tensor([[2, 3],
        [3, 4],
        [5, 6]])

In [29]:
tensor_B.T

tensor([[2, 3, 5],
        [3, 4, 6]])

In [30]:
tensor_B, tensor_B.shape

(tensor([[2, 3],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [31]:
tensor_B.T, tensor_B.T.shape

(tensor([[2, 3, 5],
         [3, 4, 6]]),
 torch.Size([2, 3]))

#the matrix multiplication operation works when tensor_B is transposed

In [32]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[11, 15, 23],
        [16, 22, 34],
        [31, 43, 67]])

### Tensor Aggregation (min, max,sum,mean,etc)

In [33]:
x=torch.arange(1,100,11)
x,x.dtype

(tensor([ 1, 12, 23, 34, 45, 56, 67, 78, 89]), torch.int64)

In [34]:
torch.min(x)

tensor(1)

In [35]:
x.min()

tensor(1)

In [36]:
torch.max(x)

tensor(89)

In [37]:
x.max()

tensor(89)

In [38]:
#torch.mean(x) # here dtype is Long(int64) so , torch cant handle long dtype

# Now we have convert long into float or smaller dtype

In [39]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [40]:
x.type(torch.float32).mean()

tensor(45.)

In [41]:
x.sum()

tensor(405)

In [42]:
torch.sum(x)

tensor(405)

### Day-3

#finding the positional min and max

In [43]:
x

tensor([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [44]:
#find position in tensor that has the minimum value with argmin()-> returns index value
x.argmin()

tensor(0)

In [45]:
x[0]

tensor(1)

In [46]:
#find
x.argmax()

tensor(8)

In [47]:
x[8]

tensor(89)

#Reshaping, stacking, squeezing and unsqueezing, permute


In [48]:
x=torch.arange(1.,10.)
x,x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
x_reshaped=x.reshape(1,7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [53]:
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
x_reshaped=x.reshape(2,9)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [55]:
x_reshaped=x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [56]:
#change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0]=15
z,x

In [57]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [58]:
x_stacked = torch.stack([x,x,x,x],dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

#torch.squeeze() -> removes all single dimensions from a target tensor


In [59]:
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [61]:
x_squeeze=x_reshaped.squeeze()

In [60]:
x_reshaped.squeeze().shape

torch.Size([9])

##torch.unsqueeze() -> adds a single dimensions from a target tensor at aspecific dim


In [62]:
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [65]:
x_unsqueeze=x_squeeze.unsqueeze(dim=1)

In [66]:
x_unsqueeze.shape

torch.Size([9, 1])

In [64]:
x_reshaped.unsqueeze(dim=1)

tensor([[[1.]],

        [[2.]],

        [[3.]],

        [[4.]],

        [[5.]],

        [[6.]],

        [[7.]],

        [[8.]],

        [[9.]]])

In [67]:
x_reshaped.unsqueeze(dim=2)

tensor([[[1.]],

        [[2.]],

        [[3.]],

        [[4.]],

        [[5.]],

        [[6.]],

        [[7.]],

        [[8.]],

        [[9.]]])

In [68]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3))

x_permuted=x_original.permute(2,0,1) # shifts axis 0->1 1->2 2 ->0

print(f"Previous Shape:  {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")



Previous Shape:  torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [70]:
x_original[0,:,:]

tensor([[0.2653, 0.3171, 0.7317],
        [0.4050, 0.6829, 0.7773],
        [0.5927, 0.9767, 0.7630],
        [0.4173, 0.6854, 0.6741],
        [0.9576, 0.2653, 0.0038],
        [0.3225, 0.4140, 0.3742],
        [0.6225, 0.1047, 0.5801],
        [0.9166, 0.2790, 0.0266],
        [0.8224, 0.0854, 0.5726],
        [0.1896, 0.3570, 0.4568],
        [0.4157, 0.5974, 0.1482],
        [0.6063, 0.9169, 0.8082],
        [0.1766, 0.7395, 0.3722],
        [0.8321, 0.3565, 0.4665],
        [0.8922, 0.4160, 0.6008],
        [0.6815, 0.0737, 0.1784],
        [0.5551, 0.0136, 0.9139],
        [0.9760, 0.2460, 0.5702],
        [0.7236, 0.5405, 0.1870],
        [0.2380, 0.5406, 0.9178],
        [0.5670, 0.0571, 0.7365],
        [0.3400, 0.7765, 0.6963],
        [0.7498, 0.0597, 0.8300],
        [0.2189, 0.6784, 0.7967],
        [0.0315, 0.9600, 0.6615],
        [0.1372, 0.3388, 0.5250],
        [0.7724, 0.7260, 0.5568],
        [0.9444, 0.4156, 0.8182],
        [0.6388, 0.4279, 0.2977],
        [0.521

In [69]:
x_original[0,0,0]

tensor(0.2653)

In [ ]:
x_original[0,0,0]=8374
x_original[0,0,0], x_permuted[0,0,0]

#selecting data from tensors

##Indexing (selecting data from tensors)
Indexing with pytorch is similar to numpy

In [71]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
x[0][0]

tensor([1, 2, 3])

In [76]:
x[0][0][0]

tensor(1)

In [75]:
x[0][0][1]

tensor(2)

In [81]:
x[1][1][1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [78]:
x[0][1][1]

tensor(5)

In [79]:
#you can also use :  to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [80]:
#get all values of 0th and 1st dimensions but index  1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

#pytorch and Numpy

#data in numpy , want in pyTorch tensor ->  torch.from_numpy(ndarray)

#pytorch tensor -> Numpy -> torch.Tensor.numpy()

In [50]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [51]:
array.dtype

dtype('float64')

In [52]:
torch.arange(1.0,8.0).dtype

torch.float32

In [82]:
array=array+1
array,tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
#tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [84]:
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))