<a href="https://colab.research.google.com/github/MohammedAdnan51/PyTorch/blob/main/Py_Torch_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)


2.1.0+cu121


Creating Range of Tensors

In [3]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
range_tensors=torch.arange(start=0,end=1000,step=120)
range_tensors

tensor([  0, 120, 240, 360, 480, 600, 720, 840, 960])

In [5]:
#creating tensors Like
ten_zeroes=torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [6]:
#flaot 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [7]:
float_32_tensor.dtype

torch.float32

In [8]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [9]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [10]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [11]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])

###Getting Information from sensors
### tensor.dtype , tensor.shape ,tensor.device

In [12]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5788, 0.6887, 0.6464, 0.5993],
        [0.3886, 0.3512, 0.2831, 0.3323],
        [0.7918, 0.0766, 0.4741, 0.8739]])

In [13]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [14]:
some_tensor.size()

torch.Size([3, 4])

In [15]:
#finding details of tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5788, 0.6887, 0.6464, 0.5993],
        [0.3886, 0.3512, 0.2831, 0.3323],
        [0.7918, 0.0766, 0.4741, 0.8739]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


manipulation of tensors

Tensors operations include:

*  Addittion

*  Subraction

*  Multiplication

*  Division

*   Matix Multiplication
















In [16]:
#create a tensor and add
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [17]:
# Multiply
tensor *10

tensor([10, 20, 30])

In [18]:
tensor-10

tensor([-9, -8, -7])

In [19]:
tensor /10

tensor([0.1000, 0.2000, 0.3000])

In [20]:
#pytorch Inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [21]:
torch.add(tensor,20)

tensor([21, 22, 23])

#Matrix Multiplication

Two main methods for  multiplication in neural networks and deep leaning:


1.   Element Wise Multiplication
2.   Matrix Multiplication(dot product)



In [22]:
#Element multiplication
print(tensor,'*',tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [23]:
#matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

#matrix multiplication by self
#  1*1 + 2 *2 + 3*3

In [24]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.92 ms, sys: 0 ns, total: 1.92 ms
Wall time: 2.37 ms


In [25]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.08 ms, sys: 9 µs, total: 1.09 ms
Wall time: 997 µs


tensor(14)

In [26]:
# we can also use "@" for matrix multiplication
tensor @ tensor
#torch.mm(tensor,tensor)

tensor(14)

In [28]:
#matrix Multiplication dealing with tensor
tensor_A =torch.tensor([[1,3],
                       [2,4],
                       [5,7]])
tensor_B =torch.tensor([[2,3],
                       [3,4],
                       [5,6]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

so the tensor_A and tensor_B can't be multiplied due to same shape

In [30]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

#To fix this shape issue we can use transpose .

In [32]:
tensor_B

tensor([[2, 3],
        [3, 4],
        [5, 6]])

In [33]:
tensor_B.T

tensor([[2, 3, 5],
        [3, 4, 6]])

In [34]:
tensor_B, tensor_B.shape

(tensor([[2, 3],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [35]:
tensor_B.T, tensor_B.T.shape

(tensor([[2, 3, 5],
         [3, 4, 6]]),
 torch.Size([2, 3]))

#the matrix multiplication operation works when tensor_B is transposed

In [37]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[11, 15, 23],
        [16, 22, 34],
        [31, 43, 67]])

### Tensor Aggregation (min, max,sum,mean,etc)

In [46]:
x=torch.arange(1,100,11)
x,x.dtype

(tensor([ 1, 12, 23, 34, 45, 56, 67, 78, 89]), torch.int64)

In [40]:
torch.min(x)

tensor(1)

In [41]:
x.min()

tensor(1)

In [42]:
torch.max(x)

tensor(89)

In [43]:
x.max()

tensor(89)

In [45]:
torch.mean(x) # here dtype is Long(int64) so , torch cant handle long dtype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

# Now we have convert long into float or smaller dtype

In [47]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [48]:
x.type(torch.float32).mean()

tensor(45.)

In [49]:
x.sum()

tensor(405)

In [50]:
torch.sum(x)

tensor(405)