<a href="https://colab.research.google.com/github/MohammedAdnan51/PyTorch/blob/main/PyTorch1-Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import  torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [2]:
 scalar=torch.tensor(7)
 scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
#vector
vec = torch.tensor([8,8])
vec

tensor([8, 8])

In [6]:

vec.shape

torch.Size([2])

In [7]:
vec.ndim

1

In [8]:
#MATRIX
MATRIX= torch.tensor([[7,8],
                  [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#TENSOR
TENSOR= torch.tensor([[[1,3,9,11],
                       [2,4,6,8],
                       [5,7,8,11],
                       [1,2,3,4],
                      [4,5,6,7],
                      [7,8,9,12]]
                      ])
TENSOR

tensor([[[ 1,  3,  9, 11],
         [ 2,  4,  6,  8],
         [ 5,  7,  8, 11],
         [ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 12]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 6, 4])

In [14]:
TENSOR[0][1][3]

tensor(8)

#Random Tensors


Random Tensors adjust thier values based on the events needed

In [15]:
random_tensor = torch.rand(3,4)
random_tensor.shape

torch.Size([3, 4])

In [17]:
from math import radians
#random tensor  with similar to an image
rand_img_size_ten=torch.rand(size=(3,224,224))
rand_img_size_ten.shape, rand_img_size_ten.ndim


(torch.Size([3, 224, 224]), 3)

In [18]:
torch.rand(size=(3,3))

tensor([[0.9924, 0.3382, 0.9096],
        [0.5337, 0.7207, 0.2996],
        [0.5799, 0.0868, 0.1349]])

In [20]:
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32